Improve device_mgr_test output
Add custom printers for GfxrReplaySettings so that I can see the
contents of the struct when a test fails.

Before

```
[ RUN      ] ValidateGfxrReplaySettingsTest.GpuTimingUseValidationLayerPass
C:\Users\hitchens\Desktop\git\dive\capture_service\device_mgr_test.cc(495): error: Value of: ValidateGfxrReplaySettings(rs, true)
Expected: is OK and has a value that gfxr replay settings eq (expected: 184-byte object <20-9E 5B-41 03-02 00-00 10-D1 5B-41 03-02 00-00 00-00 00-00 00-00 00-00 1F-00 00-00 00-00 00-00 1F-00 00-00 00-00 00-00 70-80 5B-41 03-02 00-00 70-CE 5B-41 03-02 00-00 00-00 00-00 00-00 00-00 ... 1F-00 00-00 00-00 00-00 00-CC CC-CC CC-CC CC-CC F0-65 5C-41 03-02 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 CC-CC CC-CC 00-CC CC-CC 01-CC CC-CC CC-CC CC-CC>)
  Actual: 200-byte object <B0-47 5C-41 03-02 00-00 CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC ... CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC CC-CC>, which has status UNIMPLEMENTED: this is a test

[  FAILED  ] ValidateGfxrReplaySettingsTest.GpuTimingUseValidationLayerPass (0 ms)
```

After

```
[ RUN      ] ValidateGfxrReplaySettingsTest.GpuTimingUseValidationLayerPass
C:\Users\hitchens\Desktop\git\dive\capture_service\device_mgr_test.cc(495): error: Value of: ValidateGfxrReplaySettings(rs, true)
Expected: is OK and has a value that gfxr replay settings eq (expected: GfxrReplaySettings {
  romete_capture_path: PLACEHOLDER_REMOTE_CAPTURE_PATH,
  local_download_dir: PLACEHOLDER_LOCAL_DOWNLOAD_DIR,
  run_type: GfxrReplayOptions::kGpuTiming,
  replay_flags_str: "--enable-gpu-time",
  wait_for_debugger: 0,
  metrics: [],
  loop_single_frame_count: std::nullopt,
  use_validation_layer: true,
})
  Actual: is NOT OK, which has status UNIMPLEMENTED: this is a test

[  FAILED  ] ValidateGfxrReplaySettingsTest.GpuTimingUseValidationLayerPass (0 ms)
```