Link what you use in dive_status (#733)
A target should declare public dependencies for each include in their
public headers. This way, clients will transitively get these
dependencies and don't need to manually include them.

This fixes confusing errors like this:

```
/usr/bin/ld: src/dive/common/Release/libdive_status.a(status.cpp.o): in function `Dive::StackTraceString[abi:cxx11](int)':
status.cpp:(.text+0xac): undefined reference to `absl::lts_20250512::Symbolize(void const*, char*, int)'
```

The use of absl::Symbolize in dive_status is largely an implementation
detail; clients shouldn't need to know about it and shouldn't need to be
burdened to include it in their targets.